replicaCount: 1

image:
  repository: itzg/minecraft-server
  tag: "latest"

service:
  name: minecraft
  type: LoadBalancer
  port: 25565
  targetPort: minecraft
  loadBalancerIP: "74.178.186.251"

env:
  EULA: "TRUE"
  MEMORY: "1G"
  MAX_MEMORY: "2G"
  DIFFICULTY: "easy"
  LEVEL_TYPE: "default"
  LEVEL_NAME: "world"
  SERVER_NAME: "Minecraft Server"
  MOTD: "Welcome to our Minecraft Server"
  WHITE_LIST: "false"
  OPS: "admin"
  PVP: "true"
  MAX_PLAYERS: "20"


persistence:
  enabled: true
  size: 10Gi
  storageClass: ""  # Using static PV

# Managed Identities (populated from env.yaml)
managedIdentities:
  resources:
    minecraftSTA: "minecraftw4xyz2132ts12"
  identities:
    minecraftWorkloadIdentity: "1d31f59b-d810-426c-ae57-5069ddc9e8eb"

# Kubernetes configuration
kubernetes:
  namespace: "default"
  serviceAccount: "minecraft-sa"

# Azure File CSI configuration (using workload identity)
azureFile:
  storageAccountName: "minecraftw4xyz2132ts12"
  fileShareName: "minecraft-world"
  resourceGroupName: "rg-minecraft-server-dev"
