apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minecraft-01.fullname" . }}
  labels:
    {{- include "minecraft-01.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "minecraft-01.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minecraft-01.selectorLabels" . | nindent 8 }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ .Values.kubernetes.serviceAccount }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: minecraft
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data
      {{- end }}