{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-world-pv
  labels:
    {{- include "minecraft-01.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: minecraft-world-pv-unique
    volumeAttributes:
      resourceGroup: {{ .Values.azureFile.resourceGroupName }}
      storageAccount: {{ .Values.azureFile.storageAccountName }}
      shareName: {{ .Values.azureFile.fileShareName }}
      protocol: smb
      clientID: {{ .Values.managedIdentities.identities.minecraftWorkloadIdentity }}
      # Using workload identity to fetch storage account keys (hybrid approach)
  mountOptions:
    - dir_mode=0755
    - file_mode=0644
    - uid=1000
    - gid=1000
{{- end }} 