apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kubernetes.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minecraft-01.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/use: "true"
    azure.workload.identity/client-id: {{ .Values.managedIdentities.identities.minecraftWorkloadIdentity }}
automountServiceAccountToken: true 